export const AUTH_ACTION = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_REQUEST',
  LOGIN_ERROR: 'LOGIN_REQUEST',
  LOGOUT_ACTION: 'LOGOUT_ACTION',
  IS_AUTHENTICATED: 'IS_AUTHENTICATED',
};
